version: "3.8"
services:

  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
      - ./Backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  logs: